### ISSUE TITLE
Remove/hide top bar with hki logo from home, feedback and profile views

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/open-city-helsinki#50]
It's not needed, takes up space and is not present in original concept images

![hki-app-palaute](https://user-images.githubusercontent.com/6796559/39691519-7791019c-51e6-11e8-8ef5-8edb7f0f5b8b.png)

![hki-app-profiili](https://user-images.githubusercontent.com/6796559/39691525-7a9852b4-51e6-11e8-815b-dbc8af40cb0f.png)

**Comment by Nikokoli** [comment]
Done in 2795ab824ecfd0391dd19d16e1c0a3a2060dd069
