### ISSUE TITLE
Update bottom navigation bar

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/open-city-helsinki#54]
Adapt from this concept image

- [x] proportions of icons and text within the bar
- [x] darker/lighter text/icon when selected/not selected

![hki-app-palaute](https://user-images.githubusercontent.com/6796559/39692084-757c263c-51e8-11e8-9d10-4c71fc508178.png)

**Comment by Nikokoli** [comment]
Done in d3c039a
